### ISSUE TITLE
Setup failed on OSX

### ISSUE THREAD

**Issue by pablo-mayrgundter** [vyzn-tech/dbs-acoustic-rating#2]
Just cloned and tried your setup commands..
```
> ./dev.sh setup
Submodule '.devops/devsh' (https://github.com/clecherbauer/devsh.git) registered for path '.devops/devsh'
Submodule 'api/libs/acoustic-rating-calculator' (git@github.com:vyzn-tech/acoustic-rating-calculator.git) registered for path 'api/libs/acoustic-rating-calculator'
Cloning into '/Users/pablo/c/vyzn/dbs-acoustic-rating/.devops/devsh'...
Cloning into '/Users/pablo/c/vyzn/dbs-acoustic-rating/api/libs/acoustic-rating-calculator'...
Submodule path '.devops/devsh': checked out '7a19db465d59f23585188a9783a02237a04a6c98'
remote: Enumerating objects: 72, done.
remote: Counting objects: 100% (72/72), done.
remote: Compressing objects: 100% (44/44), done.
remote: Total 70 (delta 22), reused 64 (delta 16), pack-reused 0
Unpacking objects: 100% (70/70), 125.24 KiB | 310.00 KiB/s, done.
From github.com:vyzn-tech/acoustic-rating-calculator
 * branch            a688bc08c5c754414eb7b1ba2f4c27d6d307f0f2 -> FETCH_HEAD
Submodule path 'api/libs/acoustic-rating-calculator': checked out 'a688bc08c5c754414eb7b1ba2f4c27d6d307f0f2'
.devops/devsh/dev.main.sh: line 7: declare: -A: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
```

**Comment by clecherbauer** [comment]
hey @pablo-mayrgundter 
I'm currently removing all this dependencies to my custom code - if you want you could checkout VYZN-320 and test my changes

**Comment by pablo-mayrgundter** [comment]
Hi Christian,

I wanted to follow-up and note that we had some concerns about this setup script.  Here's from Ogali at the time you originally posted:

- modifies /etc/hosts, with python script that's compiled, so can't analyze it
- exposes your privileged docker socket to said container
- assumes linux x86-64.. we're going to have some issues with M1

**Comment by clecherbauer** [comment]
hey @pablo-mayrgundter
I've removed all the custom setup by now. 

Do you know a good solution regarding the linux x86 dependency problem? I was thinking about a second docker-compose file where we point to different Dockerfiles.

**Comment by pablo-mayrgundter** [comment]
Ah, good to hear.  I did run the setup once.. is there anything I need to fixup in my /etc/hosts?

This section perhaps?
```
# Added by Docker Desktop
# To allow the same kube context to work on the host and the container:
127.0.0.1 kubernetes.docker.internal
# End of section
```

As for how to support arch-specific binaries, not really. I'll ask Ogali but he's not working full-time yet, so no promise on response time.

**Comment by clecherbauer** [comment]
The custom setup was not designed to run on macOS. That's why it did break early enough to not mess with your files :D.
This two entries in your /etc/hosts are default values from Docker-Desktop.
Sorry for the circumstances.

**Comment by pablo-mayrgundter** [comment]
Ah, ok.  Thanks!
